spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false&amp;serverTimezone=UTC
    username: postgres
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

server:
  port: 8090

logging:
  level:
    root: info

account:
  generate:
    cron: "0 0/5 * * * ?"
    count: 15
  calculate:
    cron: "0 0/5 * * * ?"
    batchSize : 1

thread-pool:
  queueCapacity: 100
  maxPoolSize: 4
  corePoolSize: 4
  threadNamePrefix: "poolThread-"